"""
Reports endpoints for NFC Campus E-Wallet System.

Provides comprehensive reporting, analytics, and export functionality.
"""

from fastapi import APIRouter, Depends, Query, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from typing import Optional
import logging
import io

from core.database import get_db
from services.report_service import ReportService
from services.export_service import ExportService
from schemas.report import (
    SummaryReportResponse,
    BoothReportResponse,
    ProductReportResponse,
    LeaderboardResponse,
    ProductLeaderboardResponse,
    AuditLogResponse,
    ExportRequest
)
from middleware.auth import require_role

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/reports")


# ============================================================================
# Summary Report
# ============================================================================

@router.get(
    "/summary",
    response_model=SummaryReportResponse,
    summary="获取总览统计报表"
)
async def get_summary_report(
    event_id: Optional[int] = Query(None, description="活动ID（可选，不填则统计所有活动）"),
    db: Session = Depends(get_db),
    current_user = Depends(require_role(["super_admin", "event_admin", "reviewer"]))
):
    """
    获取总览统计报表。
    
    统计指标：
    - 总发放额度
    - 总充值额
    - 总消费额
    - 总退款额
    - 净消费额
    - 总交易笔数
    - 参与者数量
    - 摊位数量
    
    权限要求：super_admin, event_admin, reviewer
    """
    try:
        report_service = ReportService(db)
        summary = report_service.get_summary_report(event_id)
        
        logger.info(
            f"Summary report generated by user {current_user.username} "
            f"for event_id={event_id}"
        )
        
        return summary
    
    except Exception as e:
        logger.error(f"Error generating summary report: {str(e)}", exc_info=True)
        raise HTTPException(status_code=500, detail="Failed to generate summary report")


# ============================================================================
# Booth Report
# ============================================================================

@router.get(
    "/booths",
    response_model=BoothReportResponse,
    summary="获取摊位维度报表"
)
async def get_booth_report(
    event_id: Optional[int] = Query(None, description="活动ID（可选）"),
    db: Session = Depends(get_db),
    current_user = Depends(require_role(["super_admin", "event_admin", "reviewer"]))
):
    """
    获取摊位维度报表。
    
    统计指标：
    - 营业额
    - 退款额
    - 净收入
    - 销量
    - 成本
    - 利润
    - 利润率
    
    权限要求：super_admin, event_admin, reviewer
    """
    try:
        report_service = ReportService(db)
        booth_report = report_service.get_booth_report(event_id)
        
        logger.info(
            f"Booth report generated by user {current_user.username} "
            f"for event_id={event_id}"
        )
        
        return booth_report
    
    except Exception as e:
        logger.error(f"Error generating booth report: {str(e)}", exc_info=True)
        raise HTTPException(status_code=500, detail="Failed to generate booth report")


# ============================================================================
# Product Report
# ============================================================================

@router.get(
    "/products",
    response_model=ProductReportResponse,
    summary="获取商品维度报表"
)
async def get_product_report(
    event_id: Optional[int] = Query(None, description="活动ID（可选）"),
    booth_id: Optional[int] = Query(None, description="摊位ID（可选）"),
    db: Session = Depends(get_db),
    current_user = Depends(require_role(["super_admin", "event_admin", "reviewer"]))
):
    """
    获取商品维度报表。
    
    统计指标：
    - 销量
    - 收入
    - 成本
    - 利润
    - 利润率
    
    权限要求：super_admin, event_admin, reviewer
    """
    try:
        report_service = ReportService(db)
        product_report = report_service.get_product_report(event_id, booth_id)
        
        logger.info(
            f"Product report generated by user {current_user.username} "
            f"for event_id={event_id}, booth_id={booth_id}"
        )
        
        return product_report
    
    except Exception as e:
        logger.error(f"Error generating product report: {str(e)}", exc_info=True)
        raise HTTPException(status_code=500, detail="Failed to generate product report")


# ============================================================================
# Audit Logs
# ============================================================================

@router.get(
    "/audit-logs",
    response_model=AuditLogResponse,
    summary="获取异常审计日志"
)
async def get_audit_logs(
    event_id: Optional[int] = Query(None, description="活动ID（可选）"),
    flag_type: str = Query(
        "all",
        description="标记类型（all/high_frequency_refund/large_adjustment/suspicious_operation）"
    ),
    limit: int = Query(100, description="返回数量限制", ge=1, le=1000),
    db: Session = Depends(get_db),
    current_user = Depends(require_role(["super_admin", "event_admin", "reviewer"]))
):
    """
    获取异常审计日志。
    
    标记规则：
    - high_frequency_refund: 高频退款（同一操作员在1小时内退款超过5次）
    - large_adjustment: 大额更正（adjust 类型且金额 > 1000元）
    - suspicious_operation: 可疑操作（深夜交易：22:00-06:00）
    
    权限要求：super_admin, event_admin, reviewer
    """
    try:
        report_service = ReportService(db)
        audit_logs = report_service.get_audit_logs(event_id, flag_type, limit)
        
        logger.info(
            f"Audit logs retrieved by user {current_user.username} "
            f"for event_id={event_id}, flag_type={flag_type}"
        )
        
        return audit_logs
    
    except Exception as e:
        logger.error(f"Error retrieving audit logs: {str(e)}", exc_info=True)
        raise HTTPException(status_code=500, detail="Failed to retrieve audit logs")


# ============================================================================
# Export
# ============================================================================

@router.get(
    "/export/excel",
    summary="导出报表为 Excel"
)
async def export_report_excel(
    report_type: str = Query(..., description="报表类型（summary/booths/products/transactions）"),
    event_id: Optional[int] = Query(None, description="活动ID（可选）"),
    db: Session = Depends(get_db),
    current_user = Depends(require_role(["super_admin", "event_admin", "reviewer"]))
):
    """
    导出报表为 Excel 文件。
    
    支持的报表类型：
    - summary: 总览统计
    - booths: 摊位报表
    - products: 商品报表
    - transactions: 交易流水
    
    权限要求：super_admin, event_admin, reviewer
    """
    try:
        export_service = ExportService(db)
        excel_data = export_service.export_to_excel(report_type, event_id)
        
        logger.info(
            f"Report exported by user {current_user.username} "
            f"for report_type={report_type}, event_id={event_id}"
        )
        
        # 生成文件名
        filename = f"report_{report_type}"
        if event_id:
            filename += f"_event{event_id}"
        filename += ".xlsx"
        
        # 返回 Excel 文件
        return StreamingResponse(
            io.BytesIO(excel_data),
            media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            headers={
                "Content-Disposition": f"attachment; filename={filename}"
            }
        )
    
    except ValueError as e:
        logger.warning(f"Invalid export request: {str(e)}")
        raise HTTPException(status_code=400, detail=str(e))
    
    except Exception as e:
        logger.error(f"Error exporting report: {str(e)}", exc_info=True)
        raise HTTPException(status_code=500, detail="Failed to export report")
